### PR TITLE
Add Windows cross compile support

### LINKED ISSUE #55: Compiling for windows
I was trying to cross compile uhub for windows, but i ended up with the following error:
```
[ 53%] Linking C executable autotest-bin.exe
libnetwork.a(connection.c.obj):connection.c:(.text+0x868): undefined reference to `__imp_htons'
libnetwork.a(connection.c.obj):connection.c:(.text+0x8dc): undefined reference to `__imp_htons'
libnetwork.a(dnsresolver.c.obj):dnsresolver.c:(.text+0x353): undefined reference to `__imp_getaddrinfo'
libnetwork.a(dnsresolver.c.obj):dnsresolver.c:(.text+0x47b): undefined reference to `__imp_freeaddrinfo'
libnetwork.a(ipcalc.c.obj):ipcalc.c:(.text+0x36b): undefined reference to `__imp_htons'
libnetwork.a(ipcalc.c.obj):ipcalc.c:(.text+0x41d): undefined reference to `__imp_htons'
libnetwork.a(network.c.obj):network.c:(.text+0x78): undefined reference to `__imp_WSAStartup'
libnetwork.a(network.c.obj):network.c:(.text+0xaf): undefined reference to `__imp_WSACleanup'
libnetwork.a(network.c.obj):network.c:(.text+0x114): undefined reference to `__imp_WSACleanup'
libnetwork.a(network.c.obj):network.c:(.text+0x194): undefined reference to `__imp_WSAGetLastError'
libnetwork.a(network.c.obj):network.c:(.text+0x20e): undefined reference to `__imp_setsockopt'
libnetwork.a(network.c.obj):network.c:(.text+0x271): undefined reference to `__imp_getsockopt'
libnetwork.a(network.c.obj):network.c:(.text+0x2d1): undefined reference to `__imp_ioctlsocket'
libnetwork.a(network.c.obj):network.c:(.text+0x51c): undefined reference to `__imp_closesocket'
libnetwork.a(network.c.obj):network.c:(.text+0x561): undefined reference to `__imp_shutdown'
libnetwork.a(network.c.obj):network.c:(.text+0x588): undefined reference to `__imp_shutdown'
libnetwork.a(network.c.obj):network.c:(.text+0x5af): undefined reference to `__imp_shutdown'
libnetwork.a(network.c.obj):network.c:(.text+0x62f): undefined reference to `__imp_accept'
libnetwork.a(network.c.obj):network.c:(.text+0x7e7): undefined reference to `__imp_connect'
libnetwork.a(network.c.obj):network.c:(.text+0x849): undefined reference to `__imp_socket'
libnetwork.a(network.c.obj):network.c:(.text+0x91d): undefined reference to `__imp_socket'
libnetwork.a(network.c.obj):network.c:(.text+0xa7d): undefined reference to `__imp_WSAAddressToStringA'
libnetwork.a(network.c.obj):network.c:(.text+0xb22): undefined reference to `__imp_WSAStringToAddressA'
libnetwork.a(network.c.obj):network.c:(.text+0xbf0): undefined reference to `__imp_getpeername'
libnetwork.a(network.c.obj):network.c:(.text+0xd02): undefined reference to `__imp_getsockname'
libnetwork.a(network.c.obj):network.c:(.text+0xd93): undefined reference to `__imp_recv'
libnetwork.a(network.c.obj):network.c:(.text+0xe02): undefined reference to `__imp_send'
libnetwork.a(network.c.obj):network.c:(.text+0xe66): undefined reference to `__imp_bind'
libnetwork.a(network.c.obj):network.c:(.text+0xeae): undefined reference to `__imp_listen'
libnetwork.a(select.c.obj):select.c:(.text+0x296): undefined reference to `__imp_select'
libnetwork.a(select.c.obj):select.c:(.text+0x339): undefined reference to `__WSAFDIsSet'
libnetwork.a(select.c.obj):select.c:(.text+0x35c): undefined reference to `__WSAFDIsSet'
collect2: error: ld returned 1 exit status
CMakeFiles/autotest-bin.dir/build.make:563: recipe for target 'autotest-bin.exe' failed
make[2]: *** [autotest-bin.exe] Error 1
CMakeFiles/Makefile2:68: recipe for target 'CMakeFiles/autotest-bin.dir/all' failed
make[1]: *** [CMakeFiles/autotest-bin.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

i tried googling, but the only solution i found - including ws2_32 in the target_link_libraries line - is already present. It seems it somehow doesn't find the ws2_32 lib althrough it is present:

```
find /usr/x86_64-w64-mingw32/ -name "*ws2_32*"
/usr/x86_64-w64-mingw32/lib/libws2_32.a
```

Thoughts?

### PR DESCRIPTION
**Pull request by felixbrucker**
This PR adds windows cross compile support by fixing the linking order in the `CMakeLists.txt`. A wrapper script is added to cross compile windows x64 bins and dlls from source in a docker container.

When merging please squash merge to get rid of the WIP commits.

Fixes #55

### CODE REVIEW

**Comment by tehnick** [comment]
I am sorry to say so but proposed changes look really bad from my point of view.

Starting from PR title... There is no problem with `uhub` cross-compilation when all libraries are shared libraries. In your specific case one library (`libws2_32`) was a static library. That is why you have faced with issue #55. But this is a feature specific only to your build environment.

Next. Why you added one more thirdparty library? (Happily as git submodule and not its code directly as it was [previously](https://github.com/janvidar/uhub/commit/a5b02d1672b69916fced1475e4750fd172059adb#commitcomment-816920) with sqlite.) This is an ugly solution (to bring all required libraries to own repo) which was commonly used only by developers who were working under MS Windows and did not know other ways of development. But nowdays even under MS Windows there are useful projects like MSYS, MSYS2+[MINGW-packages](https://github.com/Alexpux/MINGW-packages), [vcpkg](https://github.com/Microsoft/vcpkg) and their analogues.

As for cross-compilation for MS Windows from GNU/Linux and macOS systems, people now use projects like [MXE](https://mxe.cc/) or prepare their build environments themselves (due to different reasons). But in any case buuild environment should be separated from project sources.

**Comment by tehnick** [comment]
> What i want to provide is an easy way to get a working exe of uhub.

How about saving of all changes required to fix #55 and dropping of all other changes in this PR?

**Comment by felixbrucker** [comment]
Manually finding and building sqlite and openssl (with the correct args and stuff) doesnt seem easy to me

**Comment by tehnick** [comment]
As for docker related changes they may be discussed it next PR when this one will be merged.

**Comment by tehnick** [comment]
> Manually finding and building sqlite and openssl (with the correct args and stuff) doesnt seem easy to me

Just look at MXE project. It is really convenient.

**Comment by felixbrucker** [comment]
This stuff is over my head.

If you want to close here sure, go ahead. At least if someone wants to build uhub for windows with one command he can search the issues/prs and find this for reference to get it done.

**Pull request closed without merging**
